name: Report a documentation issue
description: Missing information in our docs? Report a documentation issue
labels:
  - documentation
body:

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please describe the inconsistency or issue you have found in
        [our documentation](https://hermaeus-project.github.io/hermaeus-operator/)
        or indicate where you feel there is a need for improvement. Furthermore,
        explain the severity of the issue, i.e., its impact on you and potentially
        other users.
#  TODO      [More](https://hermaeus-project.github.io/hermaeus-operator/contributing/reporting-a-docs-issue/#description)
    validations:
      required: true

  - type: textarea
    id: related-links
    attributes:
      label: Related links
      description: >-
        Please list all links to the sections of [our documentation](https://hermaeus-project.github.io/hermaeus-operator/)
        that are impacted by the issue you described above. If applicable,
        add screenshots. Additionally, list links to possibly related open
        and closed [issues](https://github.com/hermaeus-project/hermaeus-operator/issues)
        and [discussions](https://github.com/hermaeus-project/hermaeus-operator/discussions)
        you encountered when searching our issue tracker.
#  TODO      [More](https://hermaeus-project.github.io/hermaeus-operator/contributing/reporting-a-docs-issue/#related-links)
#      value: |-
#  TODO      - [Reporting a docs issue](https://hermaeus-project.github.io/hermaeus-operator/contributing/reporting-a-docs-issue/)

    validations:
      required: true

  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed change
      description: >-
        This field is optional. You may provide an improvement proposal for our
        documentation by describing your suggestion in the text field below or
        creating a pull request after reporting this issue referencing the issue.
# TODO       [More](https://hermaeus-project.github.io/hermaeus-operator/contributing/reporting-a-docs-issue/#proposed-change)

# TODO
#  - type: checkboxes
#    id: checklist
#    attributes:
#      label: Before submitting
#      description: >-
#        Please ensure your documentation issue report fulfills all of the
#        following requirements. If you need clarification on a specific
#        requirement, follow the link to learn about it and understand why it is
#        necessary before ticking the box. This will save the maintainers and you
#        valuable time.
#      options:
#        - label: >-
#            I have read and followed the [documentation issue guidelines](https://hermaeus-project.github.io/hermaeus-operator/contributing/reporting-a-docs-issue/).
#          required: true
#        - label: >-
#            I have attached the links to the affected sections of [the documentation](https://hermaeus-project.github.io/hermaeus-operator/contributing/reporting-a-docs-issue/#related-links)
#          required: true